// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace ECAIService
{
    public partial class Amazon2014Model
    {
        /// <summary>
        /// model input class for Amazon2014Model.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"ReviewerID")]
            public string ReviewerID { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"ASIN")]
            public string ASIN { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Overall")]
            public float Overall { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for Amazon2014Model.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"ReviewerID")]
            public string ReviewerID { get; set; }

            [ColumnName(@"ASIN")]
            public string ASIN { get; set; }

            [ColumnName(@"Overall")]
            public float Overall { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("Amazon2014Model.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
